export const horariosLaborales = [
    {
        hora:'10:00',
        disponible:true
    },
    {
        hora:'10:30',
        disponible:true
    },
    {
        hora:'11:00',
        disponible:true
    },
    {
        hora:'11:30',
        disponible:true
    },
    {
        hora:'15:00',
        disponible:true
    },
    {
        hora:'15:30',
        disponible:true
    },
    {
        hora:'16:00',
        disponible:true
    },
    {
        hora:'16:30',
        disponible:true
    },
    {
        hora:'17:00',
        disponible:true
    },
    {
        hora:'17:30',
        disponible:true
    },
] 
